### ISSUE TITLE
Add layout children feature in diagram

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse-sirius/sirius-desktop#153]
In diagram, I propose to add layout children (in the arrange toolbar menu, arrange selection toolbar menu and in Layout sub menu of contextual/diagram menu) to layout the direct children of the selected elements in their parents.

**Comment by scosta-obeo** [comment]
In some cases, an error may occur:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.action.IMenuManager.getItems()" because "arrangeMenu" is null
    at org.eclipse.sirius.diagram.ui.tools.internal.menu.DiagramEditorContextMenuProvider.disableArrangeSelectionActionFromArrangeMenu(DiagramEditorContextMenuProvider.java:319)
    at org.eclipse.sirius.diagram.ui.tools.internal.menu.DiagramEditorContextMenuProvider.updateArrangeMenuEnableActions(DiagramEditorContextMenuProvider.java:303)
    at org.eclipse.sirius.diagram.ui.tools.internal.menu.DiagramEditorContextMenuProvider.reorganizeLayoutMenu(DiagramEditorContextMenuProvider.java:254)
    at org.eclipse.sirius.diagram.ui.tools.internal.menu.DiagramEditorContextMenuProvider.lambda$0(DiagramEditorContextMenuProvider.java:128)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:323)
    at org.eclipse.sirius.diagram.ui.tools.internal.menu.DiagramEditorContextMenuProvider.buildContextMenu(DiagramEditorContextMenuProvider.java:103)
    at org.eclipse.gef.ContextMenuProvider.menuAboutToShow(ContextMenuProvider.java:61)
    at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
    at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
    at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
```

**Comment by florianbarbin** [comment]
Validated by Glenn with Capella stable 19022024
